### ISSUE TITLE
Unable initialize cluster

### ISSUE THREAD

**Issue by aforadi** [james-tn/ray-on-aml#24]
Hi,

Thank you for this library. We are trying to get this working from the example code shared in an interactive environment.

```
from azureml.core import Workspace, Run, Environment
from ray_on_aml.core import Ray_On_AML
ws = Workspace.from_config()
ray_on_aml =Ray_On_AML(ws=ws, compute_cluster ='ray-test', additional_pip_packages=['lightgbm_ray', 'sklearn'], maxnode=4)
ray = ray_on_aml.getRay(ci_is_head=False)
```

The image builds correctly. However, we receive the following error in the notebook.

```
Cancel active AML runs if any
Shutting down ray if any
Found existing cluster ray-test
Waiting cluster to start and return head node ip
..............................................................................................Cluster startup failed, check detail at run
```

And the following error inside the experiment:
```
Traceback (most recent call last):
  File "source_file.py", line 100, in <module>
    startRay(master_ip)
  File "source_file.py", line 43, in startRay
    ip = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

This error comes with both True and False for ci_is_head.

All machines are inside the same VNET.

Let me know in case anything wrong with our setup or this is an issue with the library.

Thanks a lot!

**Comment by aforadi** [comment]
@james-tn any support would be helpful. Thanks!
